### ISSUE TITLE
relative import affecting browserify

### ISSUE THREAD

**Issue by guerrerocarlos** [indutny/asn1.js#89]
This line:
https://github.com/indutny/asn1.js/blob/0abb73e0058907b6c7c2160605cd432de0e530ac/rfc/5280/index.js#L4

Is affecting other projects when using browserify, see:
https://github.com/bitpay/copay/issues/7001

**Comment by indutny** [comment]
Should be fixed now, sorry for inconvenience.

**Comment by guerrerocarlos** [comment]
Hello @indutny, did you push asn1.js@4.10.0 to npm?

**Comment by indutny** [comment]
It was pushed out in 4.9.2, prior to 4.10.0 unpublish.

**Comment by guerrerocarlos** [comment]
This package still presents the bug:

https://www.npmjs.com/package/asn1.js-rfc5280

**Comment by indutny** [comment]
@guerrerocarlos which version did you try? 2.0.1 should have the fix.
